# Objetivos 1 y 2

## Objetivo 1: Simular la amortización de préstamos bajo diferentes sistemas, concretamente francés y alemán, eligiendo el método con el que se va a continuar el proceso.

Cargamos las librerias

In [44]:
import pandas as pd
import numpy as np

Vamos a leer el CSV que hemos filtrado previamente

In [45]:
df = pd.read_csv("Data/df_filtrado.csv")

In [46]:
df

,ID,Edad,Ingresos,Monto_Inicial,Scoring_Crediticio,Meses_Empleo,Num_Creditos,Ratio_Interes,Duracion,Ratio_Deuda_Ingresos,...,Fiador,Impago,Prima,Tipo_Jornada_Laboral_Autónomo,Tipo_Jornada_Laboral_Desempleado,Tipo_Jornada_Laboral_Jornada completa,Tipo_Jornada_Laboral_Tiempo parcial,Estado_Civil_Casado,Estado_Civil_Divorciado,Estado_Civil_Soltero
0,6B4H6E,22,16000.0,10000,769,22.0,1,8.96,48.0,0.32,...,0.0,0,65.85,0,1,0,0,0,0,1
1,VKTUXP,33,38308.0,16474,699,70.0,3,14.07,36.0,0.20,...,0.0,0,260.60,0,0,1,0,1,0,0
2,5P9OVL,51,51271.0,40770,812,309.0,1,12.66,12.0,0.36,...,1.0,0,221.02,0,0,1,0,1,0,0
3,YL0W8G,30,31923.0,36707,813,43.0,1,8.96,24.0,0.32,...,0.0,0,125.00,0,0,1,0,1,0,0
4,YP8WTV,28,27373.0,86981,765,60.0,2,10.07,48.0,0.55,...,0.0,0,800.00,0,0,1,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
101881,5PM51H,29,35671.0,5681,628,27.0,2,12.11,48.0,0.10,...,1.0,0,116.89,0,0,1,0,0,0,1
101882,L0RUJT,28,22864.0,40000,752,9.0,2,10.77,48.0,0.55,...,0.0,0,607.55,0,0,1,0,1,0,0
101883,8OJZU0,35,69159.0,41795,699,65.0,2,10.41,36.0,0.29,...,0.0,0,406.82,0,0,0,1,0,0,1
101884,II8B24,39,68375.0,21847,722,170.0,2,6.26,36.0,0.14,...,1.0,0,125.32,0,0,1,0,1,0,0
101885,A8KWSO,19,22562.0,40000,779,0.0,1,6.44,24.0,0.55,...,0.0,0,156.06,0,0,0,1,0,0,1

Monto_Inicial = capital inicial del préstamo

Ratio_Interes = tipo de interés

Duracion = duración del préstamo

In [47]:
df[["Monto_Inicial", "Ratio_Interes", "Duracion"]].head(10)

   Monto_Inicial  Ratio_Interes  Duracion
0          10000           8.96      48.0
1          16474          14.07      36.0
2          40770          12.66      12.0
3          36707           8.96      24.0
4          86981          10.07      48.0
5          63406           9.83      60.0
6           3146          16.61      36.0
7          98937           7.45      48.0
8         117341           3.46      12.0
9          40000           6.48      60.0

como vemos tenemos el interes en porcentajes por lo que el la funcion lo vamos a pasar a decimal

In [48]:
def amortizacion_francesa(df):

    capital = df["Monto_Inicial"]
    interes = df["Ratio_Interes"] / 100 #dividimos entre 100 porque tenemos el interes en porcentaje
    duracion = df["Duracion"]
    interes_mensual = interes / 12

    cuota = (capital * interes_mensual) / (1 - (1 + interes_mensual)**(-duracion))

    return cuota

Hemos creado una funcion que calcula la formula de la capitalizacion francesa

In [49]:
df["Cuota_Francesa"] = amortizacion_francesa(df)

creamos una columna que se llame cuota francesa y llamamos a la función para meterla

In [50]:
df.head()

,ID,Edad,Ingresos,Monto_Inicial,Scoring_Crediticio,Meses_Empleo,Num_Creditos,Ratio_Interes,Duracion,Ratio_Deuda_Ingresos,...,Impago,Prima,Tipo_Jornada_Laboral_Autónomo,Tipo_Jornada_Laboral_Desempleado,Tipo_Jornada_Laboral_Jornada completa,Tipo_Jornada_Laboral_Tiempo parcial,Estado_Civil_Casado,Estado_Civil_Divorciado,Estado_Civil_Soltero,Cuota_Francesa
0,6B4H6E,22,16000.0,10000,769,22.0,1,8.96,48.0,0.32,...,0,65.85,0,1,0,0,0,0,1,248.660533
1,VKTUXP,33,38308.0,16474,699,70.0,3,14.07,36.0,0.20,...,0,260.60,0,0,1,0,1,0,0,563.602524
2,5P9OVL,51,51271.0,40770,812,309.0,1,12.66,12.0,0.36,...,0,221.02,0,0,1,0,1,0,0,3634.965055
3,YL0W8G,30,31923.0,36707,813,43.0,1,8.96,24.0,0.32,...,0,125.00,0,0,1,0,1,0,0,1676.276241
4,YP8WTV,28,27373.0,86981,765,60.0,2,10.07,48.0,0.55,...,0,800.00,0,0,1,0,0,0,1,2208.988068

In [51]:
def amortizacion_alemana(df):

    capital = df["Monto_Inicial"]
    interes = df["Ratio_Interes"] / 100
    intereses_mensuales = interes/12
    duracion = df["Duracion"]

    amortizacion = capital / duracion

    intereses = capital * intereses_mensuales

    cuota = amortizacion + intereses

    return cuota

In [52]:
df["Cuota_Alemana"] = amortizacion_alemana(df)

In [53]:
df

,ID,Edad,Ingresos,Monto_Inicial,Scoring_Crediticio,Meses_Empleo,Num_Creditos,Ratio_Interes,Duracion,Ratio_Deuda_Ingresos,...,Prima,Tipo_Jornada_Laboral_Autónomo,Tipo_Jornada_Laboral_Desempleado,Tipo_Jornada_Laboral_Jornada completa,Tipo_Jornada_Laboral_Tiempo parcial,Estado_Civil_Casado,Estado_Civil_Divorciado,Estado_Civil_Soltero,Cuota_Francesa,Cuota_Alemana
0,6B4H6E,22,16000.0,10000,769,22.0,1,8.96,48.0,0.32,...,65.85,0,1,0,0,0,0,1,248.660533,283.000000
1,VKTUXP,33,38308.0,16474,699,70.0,3,14.07,36.0,0.20,...,260.60,0,0,1,0,1,0,0,563.602524,650.768761
2,5P9OVL,51,51271.0,40770,812,309.0,1,12.66,12.0,0.36,...,221.02,0,0,1,0,1,0,0,3634.965055,3827.623500
3,YL0W8G,30,31923.0,36707,813,43.0,1,8.96,24.0,0.32,...,125.00,0,0,1,0,1,0,0,1676.276241,1803.537267
4,YP8WTV,28,27373.0,86981,765,60.0,2,10.07,48.0,0.55,...,800.00,0,0,1,0,0,0,1,2208.988068,2542.019725
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
101881,5PM51H,29,35671.0,5681,628,27.0,2,12.11,48.0,0.10,...,116.89,0,0,1,0,0,0,1,149.909528,175.684925
101882,L0RUJT,28,22864.0,40000,752,9.0,2,10.77,48.0,0.55,...,607.55,0,0,1,0,1,0,0,1029.358794,1192.333333
101883,8OJZU0,35,69159.0,41795,699,65.0,2,10.41,36.0,0.29,...,406.82,0,0,0,1,0,0,1,1356.666630,1523.543847
101884,II8B24,39,68375.0,21847,722,170.0,2,6.26,36.0,0.14,...,125.32,0,0,1,0,1,0,0,667.204825,720.829628
101885,A8KWSO,19,22562.0,40000,779,0.0,1,6.44,24.0,0.55,...,156.06,0,0,0,1,0,0,1,1780.765529,1881.333333

Para determinar la eleccion de cuota de amortizacion vamos a utilizar las variables ratio_deuda_ingresos, que corresponde a la deuda del prestatario en comparación con sus
ingresos y una variable que vamos a crear combinando dos que ya tenemos (cuota alemana y ingresos totales)

In [54]:
df["Ingresos_mensuales"] = df["Ingresos"]/14

Hemos dividido entre 14 en vez de entre 12 porque los españoles tienen derecho como minimo a dos pagas extra, según el Boletín Oficial del Estado y la mayoria recibe sus ingresos
en 14 cuotas (una por cada mes y las dos pagas extra mínimas)

dividimos la cuota alemana entre los ingresos mensuales lo que nos va a dar como resultado un valor que nos representa que esfuerzo supone para el cliente la primera cuota
de amortizacion alemana, cuanto mayor sea el valor de la columna "Ratio_Aleman" más esfuerzo supondra para el cliente

In [55]:
df["Ratio_aleman"]=( df["Cuota_Alemana"] / df["Ingresos_mensuales"])

In [56]:
df["Ratio_Deuda_Ingresos"].describe()

count    101886.000000
mean          0.321375
std           0.181194
min           0.100000
25%           0.140000
50%           0.290000
75%           0.550000
max           0.550000
Name: Ratio_Deuda_Ingresos, dtype: float64

Con los datos que tenemos vamos a calcular un ratio de endeudamiento si utilizaramos la amortizacion alemana para cada cliente, esto lo vamos a hacer sumando el ratio de deuda ingresos (DTI) y el Ratio Aleman. Esta operacion tiene sentido porque ambos se calculan igual

### Ratio de deuda ingresos = Pagos mensuales de deuda / Ingresos mensuales

### Ratio Aleman = Cuota Alemana/ Ingresos mensuales

Entonces la suma de estos nos va a dar el ratio de endeudamiento que tendria el cliente tras aplicarle la amortizacion alemana

In [57]:
df["Ratio_Deuda_Ingresos_Aleman"] = (df["Ratio_aleman"] + df["Ratio_Deuda_Ingresos"])

In [58]:
df.head()

,ID,Edad,Ingresos,Monto_Inicial,Scoring_Crediticio,Meses_Empleo,Num_Creditos,Ratio_Interes,Duracion,Ratio_Deuda_Ingresos,...,Tipo_Jornada_Laboral_Jornada completa,Tipo_Jornada_Laboral_Tiempo parcial,Estado_Civil_Casado,Estado_Civil_Divorciado,Estado_Civil_Soltero,Cuota_Francesa,Cuota_Alemana,Ingresos_mensuales,Ratio_aleman,Ratio_Deuda_Ingresos_Aleman
0,6B4H6E,22,16000.0,10000,769,22.0,1,8.96,48.0,0.32,...,0,0,0,0,1,248.660533,283.000000,1142.857143,0.247625,0.567625
1,VKTUXP,33,38308.0,16474,699,70.0,3,14.07,36.0,0.20,...,1,0,1,0,0,563.602524,650.768761,2736.285714,0.237829,0.437829
2,5P9OVL,51,51271.0,40770,812,309.0,1,12.66,12.0,0.36,...,1,0,1,0,0,3634.965055,3827.623500,3662.214286,1.045166,1.405166
3,YL0W8G,30,31923.0,36707,813,43.0,1,8.96,24.0,0.32,...,1,0,1,0,0,1676.276241,1803.537267,2280.214286,0.790951,1.110951
4,YP8WTV,28,27373.0,86981,765,60.0,2,10.07,48.0,0.55,...,1,0,0,0,1,2208.988068,2542.019725,1955.214286,1.300123,1.850123

El Banco de España indica que el porcentaje de ingresos netos que pueden ser destinados a las deudas nunca debe de sobrepasar el 40% de los ingresos, por lo que vamos a coger ese valor como límite. Es decir si la variable Ratio_Deuda_Ingresos_Aleman supera los 0.40 supondremos que utilizando el sistema Aleman el cliente sobrepasaria el limite recomendado por el Banco de España y entonces seleccionaremos el sistema Francés

In [59]:
df["Sistema_Elegido"] = np.where(df["Ratio_Deuda_Ingresos_Aleman"] > 0.40,"Frances","Aleman")

In [60]:
df["Sistema_Elegido"].value_counts()

Sistema_Elegido
Frances    74549
Aleman     27337
Name: count, dtype: int64

In [61]:
conteo = df["Sistema_Elegido"].value_counts()

porcentaje = conteo / len(df) * 100

print(porcentaje)

Sistema_Elegido
Frances    73.169032
Aleman     26.830968
Name: count, dtype: float64

Los resultados obtenidos tienen sentido, ya que el 73,17 % de los préstamos se han asignado al sistema frances, frente al 26,83 % al sistema aleman. Esto es coherente con nuestro criterio, puesto que el sistema aleman tiene una cuota inicial más elevada y, por tanto, es más probable que el cliente supere el límite del 40 % del ratio deuda ingresos. Por ello, resulta lógico que el sistema frances sea seleccionado para un mayor número de clientes.

## Objetivo 2: Calcular el valor presente de las cuotas pendientes a mitad del préstamo con el método seleccionado

Vamos a calcular una variable llamada mitad de prestamo para determinar en que momento del prestamo hay que calcular el valor de las cuotas, tambien vamos a crear otra que se llame cuotas pendientes que nos digar cuantas cuotas nos quedan pendientes en esa mitad del prestamos

In [62]:
df["Mitad_Prestamo"] = df["Duracion"] / 2
df["Cuotas_Pendientes"] = df["Duracion"] - df["Mitad_Prestamo"]

In [63]:
def valor_presente(df):
    capital = df["Monto_Inicial"]
    interes = df["Ratio_Interes"] / 100
    intereses_mensuales = interes / 12
    duracion = df["Duracion"]
    pagado = df["Mitad_Prestamo"]
    Capital_amortizado = capital/duracion

    if df["Sistema_Elegido"] == "Frances":
        saldo_pendiente = capital*(((1 + intereses_mensuales)**duracion - (1 + intereses_mensuales)**pagado) / ((1 + intereses_mensuales)**duracion -1) )
    elif df["Sistema_Elegido"] == "Aleman":
        saldo_pendiente = capital-(pagado*Capital_amortizado)
    return saldo_pendiente

In [66]:
df["Saldo_Pendiente"] = df.apply(valor_presente, axis=1)

In [68]:
df.head(50)

,ID,Edad,Ingresos,Monto_Inicial,Scoring_Crediticio,Meses_Empleo,Num_Creditos,Ratio_Interes,Duracion,Ratio_Deuda_Ingresos,...,Estado_Civil_Soltero,Cuota_Francesa,Cuota_Alemana,Ingresos_mensuales,Ratio_aleman,Ratio_Deuda_Ingresos_Aleman,Sistema_Elegido,Mitad_Prestamo,Cuotas_Pendientes,Saldo_Pendiente
0,6B4H6E,22,16000.0,10000,769,22.0,1,8.96,48.0,0.32,...,1,248.660533,283.000000,1142.857143,0.247625,0.567625,Frances,24.0,24.0,5445.153952
1,VKTUXP,33,38308.0,16474,699,70.0,3,14.07,36.0,0.20,...,0,563.602524,650.768761,2736.285714,0.237829,0.437829,Frances,18.0,18.0,9097.996675
2,5P9OVL,51,51271.0,40770,812,309.0,1,12.66,12.0,0.36,...,0,3634.965055,3827.623500,3662.214286,1.045166,1.405166,Frances,6.0,6.0,21026.593666
3,YL0W8G,30,31923.0,36707,813,43.0,1,8.96,24.0,0.32,...,0,1676.276241,1803.537267,2280.214286,0.790951,1.110951,Frances,12.0,12.0,19172.138765
4,YP8WTV,28,27373.0,86981,765,60.0,2,10.07,48.0,0.55,...,1,2208.988068,2542.019725,1955.214286,1.300123,1.850123,Frances,24.0,24.0,47837.159576
5,F9YNI5,54,44800.0,63406,642,359.0,2,9.83,60.0,0.38,...,0,1341.892530,1576.167483,3200.000000,0.492552,0.872552,Frances,30.0,30.0,35563.386181
6,98XK3H,31,19639.0,3146,688,106.0,2,16.61,36.0,0.10,...,0,111.553804,130.934772,1402.785714,0.093339,0.193339,Aleman,18.0,18.0,1573.000000
7,AKMVZ2,41,38641.0,98937,765,306.0,2,7.45,48.0,0.55,...,0,2389.880107,2675.421375,2760.071429,0.969330,1.519330,Frances,24.0,24.0,53135.769881
8,XWXHI1,45,40023.0,117341,735,260.0,3,3.46,12.0,0.55,...,0,9962.647832,10116.749883,2858.785714,3.538828,4.088828,Frances,6.0,6.0,59177.256980
9,BJ8987,31,48248.0,40000,819,19.0,1,6.48,60.0,0.47,...,0,782.271265,882.666667,3446.285714,0.256121,0.726121,Frances,30.0,30.0,21612.136410
10,3BGF0X,29,19449.0,91977,808,71.0,4,6.33,24.0,0.55,...,1,4090.167189,4317.553675,1389.214286,3.107911,3.657911,Frances,12.0,12.0,47439.728496
11,0VPOTA,36,61364.0,70709,566,83.0,2,10.30,36.0,0.22,...,0,2291.552744,2571.057806,4383.142857,0.586579,0.806579,Frances,18.0,18.0,38068.629822
12,DFWIZR,64,61460.0,136913,668,389.0,1,11.60,24.0,0.55,...,0,6419.425088,7028.200667,4390.000000,1.600957,2.150957,Frances,12.0,12.0,72403.526593
13,57AKEJ,49,55043.0,150000,823,303.0,4,12.95,36.0,0.55,...,0,5050.481090,5785.416667,3931.642857,1.471501,2.021501,Frances,18.0,18.0,82222.895072
14,044S1L,49,49443.0,4363,455,402.0,2,10.84,12.0,0.10,...,0,385.283632,402.995767,3531.642857,0.114110,0.214110,Aleman,6.0,6.0,2181.500000
15,7G9O17,39,77018.0,66477,699,127.0,2,9.76,48.0,0.27,...,0,1678.376753,1925.617100,5501.285714,0.350030,0.620030,Frances,24.0,24.0,36459.318151
16,2QGAEX,47,31599.0,40000,617,390.0,2,10.61,60.0,0.47,...,0,861.937301,1020.333333,2257.071429,0.452061,0.922061,Frances,30.0,30.0,22625.600888
17,7XD0MJ,52,49441.0,21882,797,414.0,3,15.44,36.0,0.10,...,0,763.270110,889.381733,3531.500000,0.251842,0.351842,Aleman,18.0,18.0,10941.000000
18,G7EOG9,38,38067.0,30370,649,221.0,4,10.26,24.0,0.14,...,0,1405.068695,1525.080167,2719.071429,0.560883,0.700883,Frances,12.0,12.0,15960.005204
19,MOUIW9,34,55062.0,41005,696,53.0,3,11.25,12.0,0.17,...,1,3628.873355,3801.505208,3933.000000,0.966566,1.136566,Frances,6.0,6.0,21076.296742
20,1FC8XF,35,73101.0,46889,737,84.0,3,6.95,48.0,0.24,...,0,1121.728079,1248.419625,5221.500000,0.239092,0.479092,Frances,24.0,24.0,25066.596606
21,SGRLPQ,54,54465.0,55928,649,398.0,1,12.59,48.0,0.35,...,0,1489.052242,1751.944600,3890.357143,0.450330,0.800330,Frances,24.0,24.0,31448.128504
22,DROSEQ,38,64286.0,237184,746,198.0,2,11.50,60.0,0.55,...,0,5216.294588,6226.080000,4591.857143,1.355896,1.905896,Frances,30.0,30.0,135443.616726
23,ZJ395E,46,74757.0,221677,731,361.0,1,13.40,12.0,0.55,...,0,19841.210969,20948.476500,5339.785714,3.923093,4.473093,Frances,6.0,6.0,114529.645953
24,213CAB,53,58028.0,62707,740,410.0,1,13.56,36.0,0.19,...,0,2129.800318,2450.450211,4144.857143,0.591203,0.781203,Frances,18.0,18.0,34513.504310
25,8DT9LS,24,19308.0,3000,650,35.0,1,12.30,12.0,0.10,...,1,266.967577,280.750000,1379.142857,0.203568,0.303568,Aleman,6.0,6.0,1500.000000
26,VH8EDV,54,46429.0,13058,645,448.0,3,12.63,24.0,0.24,...,0,618.534174,681.518783,3316.357143,0.205502,0.445502,Frances,12.0,12.0,6938.613009
27,V2P8J1,34,42214.0,77155,695,46.0,2,11.28,36.0,0.55,...,0,2536.198584,2868.451444,3015.285714,0.951303,1.501303,Frances,18.0,18.0,41818.256903
28,KVV2QG,46,32980.0,13943,652,279.0,1,17.58,48.0,0.15,...,0,406.521925,494.744117,2355.714286,0.210019,0.360019,Aleman,24.0,24.0,6971.500000
29,AHUDEE,48,65942.0,11597,608,345.0,2,4.70,12.0,0.15,...,0,991.196339,1011.838250,4710.142857,0.214821,0.364821,Aleman,6.0,6.0,5798.500000
30,AUSB7N,38,32179.0,21365,752,143.0,2,9.28,60.0,0.14,...,0,446.411242,521.306000,2298.500000,0.226803,0.366803,Aleman,30.0,30.0,10682.500000
31,ALCJQM,19,21677.0,8899,702,0.0,1,17.03,24.0,0.23,...,1,440.114997,497.083308,1548.357143,0.321039,0.551039,Frances,12.0,12.0,4824.817710
32,8MIL9S,31,42575.0,36612,772,44.0,1,8.73,60.0,0.55,...,0,755.216267,876.552300,3041.071429,0.288238,0.838238,Frances,30.0,30.0,20288.604109
33,WNTKIM,60,37823.0,40000,739,484.0,1,17.16,48.0,0.24,...,0,1157.515488,1405.333333,2701.642857,0.520177,0.760177,Frances,24.0,24.0,23375.094985
34,UERFAW,31,30512.0,40000,739,55.0,1,6.17,24.0,0.55,...,1,1775.890048,1872.333333,2179.428571,0.859094,1.409094,Frances,12.0,12.0,20615.225049
35,62ULKD,43,27665.0,30830,812,274.0,1,12.21,60.0,0.25,...,0,689.072483,827.528583,1976.071429,0.418775,0.668775,Frances,30.0,30.0,17737.997144
36,UAYQYS,28,24055.0,40000,661,18.0,2,9.58,48.0,0.55,...,1,1006.454294,1152.666667,1718.214286,0.670852,1.220852,Frances,24.0,24.0,21902.621535
37,LFGCNI,53,44445.0,28726,612,371.0,2,3.40,12.0,0.13,...,0,2438.148440,2475.223667,3174.642857,0.779686,0.909686,Frances,6.0,6.0,14484.909944
38,MC61L0,35,42082.0,8297,579,150.0,4,4.73,24.0,0.10,...,0,362.998496,378.412342,3005.857143,0.125892,0.225892,Aleman,12.0,12.0,4148.500000
39,I6GXQH,33,54233.0,60795,719,62.0,2,10.10,60.0,0.29,...,1,1294.707478,1524.941250,3873.785714,0.393657,0.683657,Frances,30.0,30.0,34199.115881
40,YYBNIG,40,41312.0,40000,611,230.0,1,7.80,48.0,0.54,...,0,972.766031,1093.333333,2950.857143,0.370514,0.910514,Frances,24.0,24.0,21551.826354
41,36XL7F,40,34128.0,64564,608,216.0,1,11.17,60.0,0.43,...,0,1409.257770,1677.049900,2437.714286,0.687960,1.117960,Frances,30.0,30.0,36739.860844
42,D0G35O,35,37352.0,13137,741,208.0,2,19.89,24.0,0.10,...,0,667.912428,765.120775,2668.000000,0.286777,0.386777,Aleman,12.0,12.0,6568.500000
43,6IHNMK,39,30700.0,122052,758,252.0,1,7.19,36.0,0.55,...,0,3779.223255,4121.628233,2192.857143,1.879570,2.429570,Frances,18.0,18.0,64303.849800
44,LYO3SG,64,28278.0,52465,626,482.0,1,10.58,36.0,0.55,...,0,1707.220489,1919.927528,2019.857143,0.950526,1.500526,Frances,18.0,18.0,28300.625450
45,0BX3WF,54,31560.0,38157,659,441.0,1,15.08,48.0,0.52,...,0,1063.485869,1274.443800,2254.285714,0.565343,1.085343,Frances,24.0,24.0,21916.397572
46,W6D6B0,42,49383.0,40000,666,243.0,2,16.16,24.0,0.19,...,0,1961.583777,2205.333333,3527.357143,0.625208,0.815208,Frances,12.0,12.0,21601.777681
47,JMU2ZH,43,55963.0,21302,731,261.0,2,6.48,24.0,0.21,...,0,948.731703,1002.614133,3997.357143,0.250819,0.460819,Frances,12.0,12.0,10995.044259
48,TYJU7U,54,42538.0,19244,713,450.0,1,11.09,60.0,0.20,...,1,419.275451,498.579967,3038.428571,0.164091,0.364091,Aleman,30.0,30.0,9622.000000
49,YBFXTR,42,52866.0,34064,549,290.0,3,6.29,36.0,0.13,...,0,1040.774766,1124.774356,3776.142857,0.297863,0.427863,Frances,18.0,18.0,17832.795265