Cargamos las librerias

In [15]:
import pandas as pd

Vamos a leer el CSV que hemos filtrado previamente

In [16]:
df = pd.read_csv("Data/df_filtrado.csv")

In [17]:
df

,ID,Edad,Ingresos,Monto_Inicial,Scoring_Crediticio,Meses_Empleo,Num_Creditos,Ratio_Interes,Duracion,Ratio_Deuda_Ingresos,...,Fiador,Impago,Prima,Tipo_Jornada_Laboral_Autónomo,Tipo_Jornada_Laboral_Desempleado,Tipo_Jornada_Laboral_Jornada completa,Tipo_Jornada_Laboral_Tiempo parcial,Estado_Civil_Casado,Estado_Civil_Divorciado,Estado_Civil_Soltero
0,6B4H6E,22,16000.0,10000,769,22.0,1,8.96,48.0,0.32,...,0.0,0,65.85,0,1,0,0,0,0,1
1,VKTUXP,33,38308.0,16474,699,70.0,3,14.07,36.0,0.20,...,0.0,0,260.60,0,0,1,0,1,0,0
2,5P9OVL,51,51271.0,40770,812,309.0,1,12.66,12.0,0.36,...,1.0,0,221.02,0,0,1,0,1,0,0
3,YL0W8G,30,31923.0,36707,813,43.0,1,8.96,24.0,0.32,...,0.0,0,125.00,0,0,1,0,1,0,0
4,YP8WTV,28,27373.0,86981,765,60.0,2,10.07,48.0,0.55,...,0.0,0,800.00,0,0,1,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
101881,5PM51H,29,35671.0,5681,628,27.0,2,12.11,48.0,0.10,...,1.0,0,116.89,0,0,1,0,0,0,1
101882,L0RUJT,28,22864.0,40000,752,9.0,2,10.77,48.0,0.55,...,0.0,0,607.55,0,0,1,0,1,0,0
101883,8OJZU0,35,69159.0,41795,699,65.0,2,10.41,36.0,0.29,...,0.0,0,406.82,0,0,0,1,0,0,1
101884,II8B24,39,68375.0,21847,722,170.0,2,6.26,36.0,0.14,...,1.0,0,125.32,0,0,1,0,1,0,0
101885,A8KWSO,19,22562.0,40000,779,0.0,1,6.44,24.0,0.55,...,0.0,0,156.06,0,0,0,1,0,0,1

Monto_Inicial = capital inicial del préstamo

Ratio_Interes = tipo de interés

Duracion = duración del préstamo

In [18]:
df[["Monto_Inicial", "Ratio_Interes", "Duracion"]].head(10)

   Monto_Inicial  Ratio_Interes  Duracion
0          10000           8.96      48.0
1          16474          14.07      36.0
2          40770          12.66      12.0
3          36707           8.96      24.0
4          86981          10.07      48.0
5          63406           9.83      60.0
6           3146          16.61      36.0
7          98937           7.45      48.0
8         117341           3.46      12.0
9          40000           6.48      60.0

como vemos tenemos el interes en porcentajes por lo que el la funcion lo vamos a pasar a decimal

In [19]:
def amortizacion_francesa(df):

    capital = df["Monto_Inicial"]
    interes = df["Ratio_Interes"] / 100 #dividimos entre 100 porque tenemos el interes en porcentaje
    duracion = df["Duracion"]
    interes_mensual = interes / 12

    cuota = (capital * interes_mensual) / (1 - (1 + interes_mensual)**(-duracion))

    return cuota

Hemos creado una funcion que calcula la formula de la capitalizacion francesa

In [20]:
df["Cuota_Francesa"] = amortizacion_francesa(df)

creamos una columna que se llame cuota francesa y llamamos a la función para meterla

In [21]:
df.head()

,ID,Edad,Ingresos,Monto_Inicial,Scoring_Crediticio,Meses_Empleo,Num_Creditos,Ratio_Interes,Duracion,Ratio_Deuda_Ingresos,...,Impago,Prima,Tipo_Jornada_Laboral_Autónomo,Tipo_Jornada_Laboral_Desempleado,Tipo_Jornada_Laboral_Jornada completa,Tipo_Jornada_Laboral_Tiempo parcial,Estado_Civil_Casado,Estado_Civil_Divorciado,Estado_Civil_Soltero,Cuota_Francesa
0,6B4H6E,22,16000.0,10000,769,22.0,1,8.96,48.0,0.32,...,0,65.85,0,1,0,0,0,0,1,248.660533
1,VKTUXP,33,38308.0,16474,699,70.0,3,14.07,36.0,0.20,...,0,260.60,0,0,1,0,1,0,0,563.602524
2,5P9OVL,51,51271.0,40770,812,309.0,1,12.66,12.0,0.36,...,0,221.02,0,0,1,0,1,0,0,3634.965055
3,YL0W8G,30,31923.0,36707,813,43.0,1,8.96,24.0,0.32,...,0,125.00,0,0,1,0,1,0,0,1676.276241
4,YP8WTV,28,27373.0,86981,765,60.0,2,10.07,48.0,0.55,...,0,800.00,0,0,1,0,0,0,1,2208.988068

In [22]:
def amortizacion_alemana(df):

    capital = df["Monto_Inicial"]
    interes = df["Ratio_Interes"] / 100
    intereses_mensuales = interes/12
    duracion = df["Duracion"]

    amortizacion = capital / duracion

    intereses = capital * intereses_mensuales

    cuota = amortizacion + intereses

    return cuota

In [23]:
df["Cuota_Alemana"] = amortizacion_alemana(df)

In [24]:
df

,ID,Edad,Ingresos,Monto_Inicial,Scoring_Crediticio,Meses_Empleo,Num_Creditos,Ratio_Interes,Duracion,Ratio_Deuda_Ingresos,...,Prima,Tipo_Jornada_Laboral_Autónomo,Tipo_Jornada_Laboral_Desempleado,Tipo_Jornada_Laboral_Jornada completa,Tipo_Jornada_Laboral_Tiempo parcial,Estado_Civil_Casado,Estado_Civil_Divorciado,Estado_Civil_Soltero,Cuota_Francesa,Cuota_Alemana
0,6B4H6E,22,16000.0,10000,769,22.0,1,8.96,48.0,0.32,...,65.85,0,1,0,0,0,0,1,248.660533,283.000000
1,VKTUXP,33,38308.0,16474,699,70.0,3,14.07,36.0,0.20,...,260.60,0,0,1,0,1,0,0,563.602524,650.768761
2,5P9OVL,51,51271.0,40770,812,309.0,1,12.66,12.0,0.36,...,221.02,0,0,1,0,1,0,0,3634.965055,3827.623500
3,YL0W8G,30,31923.0,36707,813,43.0,1,8.96,24.0,0.32,...,125.00,0,0,1,0,1,0,0,1676.276241,1803.537267
4,YP8WTV,28,27373.0,86981,765,60.0,2,10.07,48.0,0.55,...,800.00,0,0,1,0,0,0,1,2208.988068,2542.019725
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
101881,5PM51H,29,35671.0,5681,628,27.0,2,12.11,48.0,0.10,...,116.89,0,0,1,0,0,0,1,149.909528,175.684925
101882,L0RUJT,28,22864.0,40000,752,9.0,2,10.77,48.0,0.55,...,607.55,0,0,1,0,1,0,0,1029.358794,1192.333333
101883,8OJZU0,35,69159.0,41795,699,65.0,2,10.41,36.0,0.29,...,406.82,0,0,0,1,0,0,1,1356.666630,1523.543847
101884,II8B24,39,68375.0,21847,722,170.0,2,6.26,36.0,0.14,...,125.32,0,0,1,0,1,0,0,667.204825,720.829628
101885,A8KWSO,19,22562.0,40000,779,0.0,1,6.44,24.0,0.55,...,156.06,0,0,0,1,0,0,1,1780.765529,1881.333333

Para determinar la eleccion de cuota de amortizacion vamos a utilizar las variables ratio_deuda_ingresos, que corresponde a la deuda del prestatario en comparación con sus
ingresos y una variable que vamos a crear combinando dos que ya tenemos (cuota alemana y ingresos totales)

In [25]:
df["Ingresos_mensuales"] = df["Ingresos"]/14

Hemos dividido entre 14 en vez de entre 12 porque los españoles tienen derecho como minimo a dos pagas extra, según el Boletín Oficial del Estado y la mayoria recibe sus ingresos
en 14 cuotas (una por cada mes y las dos pagas extra mínimas)

dividimos la cuota alemana entre los ingresos mensuales lo que nos va a dar como resultado un valor que nos representa que esfuerzo supone para el cliente la primera cuota
de amortizacion alemana, cuanto mayor sea el valor de la columna "Ratio_Aleman" más esfuerzo supondra para el cliente

In [26]:
df["Ratio_aleman"]=( df["Cuota_Alemana"] / df["Ingresos_mensuales"])

In [30]:
df["Ratio_Deuda_Ingresos"].describe()

count    101886.000000
mean          0.321375
std           0.181194
min           0.100000
25%           0.140000
50%           0.290000
75%           0.550000
max           0.550000
Name: Ratio_Deuda_Ingresos, dtype: float64

Con los datos que tenemos vamos a calcular un ratio de endeudamiento si utilizaramos la amortizacion alemana para cada cliente, esto lo vamos a hacer sumando el ratio de deuda ingresos (DTI) y el Ratio Aleman. Esta operacion tiene sentido porque ambos se calculan igual

## Ratio de deuda ingresos = Pagos mensuales de deuda / Ingresos mensuales

## Ratio Aleman = Cuota Alemana/ Ingresos mensuales

Entonces la suma de estos nos va a dar el ratio de endeudamiento que tendria el cliente tras aplicarle la amortizacion alemana

In [31]:
df["Ratio_Deuda_Ingresos_Aleman"] = (df["Ratio_aleman"] + df["Ratio_Deuda_Ingresos"])

In [33]:
df.head()

,ID,Edad,Ingresos,Monto_Inicial,Scoring_Crediticio,Meses_Empleo,Num_Creditos,Ratio_Interes,Duracion,Ratio_Deuda_Ingresos,...,Tipo_Jornada_Laboral_Jornada completa,Tipo_Jornada_Laboral_Tiempo parcial,Estado_Civil_Casado,Estado_Civil_Divorciado,Estado_Civil_Soltero,Cuota_Francesa,Cuota_Alemana,Ingresos_mensuales,Ratio_aleman,Ratio_Deuda_Ingresos_Aleman
0,6B4H6E,22,16000.0,10000,769,22.0,1,8.96,48.0,0.32,...,0,0,0,0,1,248.660533,283.000000,1142.857143,0.247625,0.567625
1,VKTUXP,33,38308.0,16474,699,70.0,3,14.07,36.0,0.20,...,1,0,1,0,0,563.602524,650.768761,2736.285714,0.237829,0.437829
2,5P9OVL,51,51271.0,40770,812,309.0,1,12.66,12.0,0.36,...,1,0,1,0,0,3634.965055,3827.623500,3662.214286,1.045166,1.405166
3,YL0W8G,30,31923.0,36707,813,43.0,1,8.96,24.0,0.32,...,1,0,1,0,0,1676.276241,1803.537267,2280.214286,0.790951,1.110951
4,YP8WTV,28,27373.0,86981,765,60.0,2,10.07,48.0,0.55,...,1,0,0,0,1,2208.988068,2542.019725,1955.214286,1.300123,1.850123